### ISSUE TITLE
Investigate using AWS VPC Traffic Mirroring

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/RPCMirror#16]
Looks like the VPC Traffic Mirroring is pretty straightforward. It uses VxLAN technology, which is a virtual VLAN technique using UDP/IP encapsulation over underlay networks.

To enable traffic mirroring, we'd do the following:
* Create a Traffic Mirror source, and connect it to an existing network interface (e.g. the VISTA EC2 instance ENI)
* Create an assign a Traffic Mirror traffic filter to the source
* Create a Traffic Mirror session, which points the source to a target for the VxLAN packets.

We could convert the RPC Mirror into a VxLAN packet parser. By limiting the mirrored traffic to **only** the traffic intended for the target VISTA RPC broker TCP port, we can (hopefully) ensure that we're only picking up RPC traffic.

I currently have a 

## Tasks
- [ ] Acquire VAEC AWS account privileges to create VPC Traffic Mirror resources
- [ ] Test and verify the operational mechanics of a simple VPC Traffic Mirror stack:
   - Source
   - Filter
   - Session (target)
- [ ] Investigate the format and contents of the VxLAN packets received by creating a simple UDP socket listener
- [ ] Attempt to decode RPC packets from encapsulated payloads
- [ ] Rework the RPC Mirror to become a VxLAN packet analyzer

## Notes
* [AWS VPC Traffic Mirroring](https://aws.amazon.com/about-aws/whats-new/2019/09/announcing-amazon-vpc-traffic-mirroring-for-aws-govcloud-us-regions/)
* [Cisco VxLAN Whitepaper](https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/white-paper-c11-729383.html)

**Comment by mfuroyama** [comment]
## Notes
* Source Elastic Network Interface must be attached to a [Nitro-based EC2 instance](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances)
* Source and target must be in the same VPC

**Comment by mfuroyama** [comment]
Strategy is to use `node-pcap` with the following process flow:
* Read and decode the UDP encapsulation of the VxLAN packet
* Manually read out the VxLAN header
* Create a new PCAP packet structure with the encapsulated Ethernet/IPv4/TCP packet payload
* Use the `node-pcap` decoder to decode the new packet
* Leverage the `node-pcap` TCP Tracker to inspect data sent on the socket.
